project:
  type: website
  render:
    - index.qmd
    - get-started.qmd
    - get-started/**/*.qmd
    - pages/**/*.qmd

format:
  html:
    theme: minty
    toc: true
    toc-expand: 4
    toc-depth: 4
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/(?:www\.)*(silvanova\.github\.io)\/.*$'

website:
  title: "Silva Nova MAW"
  page-navigation: true
  bread-crumbs: false
  navbar:
    background: primary
    search: true
    pinned: true
    tools:
      - icon: twitter
        href: https://twitter.com/SilvaNova_NNF
      - icon: github
        href: https://github.com/Silvanova/Common_scripts

    left:
      - text: "Get started"
        menu:
          - text: "Get started"
            href: get-started.qmd
          - text: "Install R and packages"
            href: get-started/install.qmd
          - text: "Data preparation"
            href: get-started/data-prep.qmd

      - text: "Handling OTU tables"
        menu:
          - text: "Handling OTU tables"
            href: pages/OTU.tables.qmd
          - text: "Controls"
            file: pages/control.qmd
          - text: "Global filtering"
            file: pages/filter.rare.qmd
          - text: "Taxonomy filtering"
            href: pages/taxonomy.qmd
          - text: "Normalization and rarefaction"
            file: pages/normalize.qmd

      - text: "Statistical Analyses"
        menu:
          - text: "Statistical Analyses"
            href: pages/stats.qmd
          - text: "Statistical Analyses"
            file: pages/stats.qmd
          - text: "Alpha diversity"
            file: pages/alpha.div.qmd
          - text: "Beta diversity"
            file: pages/beta.div.qmd
          - text: "Differential abundance"
            file: pages/diff.abund.qmd

  sidebar:
    - title: "Silva Nova MAW"
      style: "docked"
      background: light
      logo: images/Silva Nova MAW logo.png
      collapse-level: 3
      align: left
      contents:
        - file: index.qmd
          text: " "

    - title: "Get started"
      contents:
        - section: "Get started"
          file: get-started.qmd
          contents:
            - href: get-started/install.qmd
              text: "Install R and packages"
            - href: get-started/data-prep.qmd
              text: "Data preparation"

    - title: "Handling OTU tables"
      contents:
        - file: pages/OTU.tables.qmd
          text: "Handling OTU tables"
        - file: pages/control.qmd
          text: "Controls"
        - file: pages/filter.rare.qmd
          text: "Global filtering"
        - href: pages/taxonomy.qmd
          text: "Taxonomy filtering"
        - file: pages/normalize.qmd
          text: "Normalization and rarefaction"


    - title: "Statistical Analyses"
      contents:
        - file: pages/stats.qmd
          text: "Statistical Analyses"
        - file: pages/alpha.div.qmd
          text: "Alpha diversity"
        - file: pages/beta.div.qmd
          text: "Beta diversity"
        - file: pages/diff.abund.qmd
          text: "Differential abundance"
