project:
  type: website
  render:
    - index.qmd
    - get-started.qmd
    - get-started/**/*.qmd
    - otu-tables.qmd
    - otu-tables/**/*.qmd
    - stats.qmd
    - stats/**/*.qmd

format:
  html:
    theme: minty
    toc: true
    toc-expand: 4
    toc-depth: 4
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/(?:www\.)*(silvanova\.github\.io)\/.*$'

website:
  title: "Silva Nova MAW"
  page-navigation: true
  # bread-crumbs: false
  navbar:
    background: primary
    search: true
    pinned: true
    tools:
      - icon: twitter
        href: https://twitter.com/SilvaNova_NNF
      - icon: github
        href: https://github.com/Silvanova/Common_scripts

# TABS IN NAVIGATION BAR (TOP)

    left:
      - text: "Get started"
        menu:
          - text: "Get started"
            href: get-started.qmd
          - text: "Install R and packages"
            href: get-started/install.qmd
          - text: "Data preparation"
            href: get-started/data-prep.qmd

      - text: "Handling OTU tables"
        menu:
          - text: "Controls"
            file: otu-tables/controls.qmd
          - text: "Filtering"
            file: otu-tables/filter.qmd
          - text: "Rarefaction & Normalization"
            file: otu-tables/rare-norm.qmd

      - text: "Statistical Analyses"
        menu:
          - text: "Statistical Analyses"
            href: stats.qmd
          - text: "Alpha diversity"
            file: stats/alpha-div.qmd
          - text: "Beta diversity"
            file: stats/beta-div.qmd
          - text: "Differential abundance"
            file: stats/diff-abund.qmd

# TABS IN SIDEBAR

  sidebar:
    - title: "Silva Nova MAW"
      style: "docked"
      background: light
      logo: images/Silva Nova MAW logo.png
      collapse-level: 3
      align: left
      contents:
        - file: index.qmd
          text: " "

    - title: "Get started"
      contents:
        - section: "Get started"
          file: get-started.qmd
          contents:
            - href: get-started/install.qmd
              text: "Install R and packages"
            - href: get-started/data-prep.qmd
              text: "Data preparation"

    - title: "Handling OTU tables"
      contents:

        - section: "Controls"
          file: otu-tables/controls.qmd
          contents:
          - text: "Positive controls"
            file: otu-tables/controls-positive.qmd
          - text: "Negative controls"
            file: otu-tables/controls-negative.qmd

        - section: "Filtering"
          file: otu-tables/filter.qmd
          contents:
          - text: "Global filtering"
            file: otu-tables/filter/global.qmd
          # - section: "Global filtering"
          #   contents:
          #   - text: "Singletons and rare OTUs"
          #     file: otu-tables/filter/singletons-rare.qmd
          #   - text: "Scarce features"
          #     file: otu-tables/filter/scarce.qmd

          - section: "Taxonomy filtering"
            contents:
            - text: "Bacteria and Archaea (16S)"
              href: otu-tables/filter/16S.qmd
            - text: "Fungi (ITS)"
              href: otu-tables/filter/ITS.qmd
            - text: "Soil animals (CO1)"
              href: otu-tables/filter/CO1.qmd

        - section: "Rarefaction & Normalization"
          file: otu-tables/rare-norm.qmd
          contents:
          - text: "Rarefaction"
            file: otu-tables/rarefy.qmd
          - text: "Normalizations"
            file: otu-tables/normalize.qmd


    - title: "Statistical Analyses"
      contents:
        - section: "Statistical Analyses"
          file: stats.qmd
          contents:
          - text: "Alpha diversity"
            file: stats/alpha-div.qmd
          - text: "Beta diversity"
            file: stats/beta-div.qmd
          - text: "Differential abundance"
            file: stats/diff-abund.qmd
